[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# HTTPS Enforcement - Redirect all HTTP to HTTPS
[[redirects]]
  from = "http://your-domain.netlify.app/*"
  to = "https://your-domain.netlify.app/:splat"
  status = 301
  force = true

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    # HSTS - Force HTTPS for 1 year
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # Prevent MIME type sniffing
    X-Content-Type-Options = "nosniff"
    
    # Prevent clickjacking
    X-Frame-Options = "DENY"
    
    # XSS Protection
    X-XSS-Protection = "1; mode=block"
    
    # Referrer Policy
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Permissions Policy
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
    # Content Security Policy
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval';
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https:;
      font-src 'self' data:;
      connect-src 'self' https:;
      frame-ancestors 'none';
      base-uri 'self';
      form-action 'self'
    """

# Cache static assets for 1 year
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers for API routes (if any)
[[headers]]
  for = "/api/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
