[build]
builder = "nixpacks"

[build.nixpacksConfig]
buildCmd = "echo 'Skipping build for API server only'"

[deploy]
startCommand = "node server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
